"""Make primary_language nullable in Repository

Revision ID: df396cc5aa21
Revises: fad84231921f
Create Date: 2026-01-19 09:50:27.884839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df396cc5aa21'
down_revision = 'fad84231921f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.alter_column('primary_language',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.alter_column('primary_language',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
